tulika-99/DS_Algorithms

README.md
=> Initialize

Trees/Inorder_Traversal/InorderTraversal_Python3.py
This is the implementation of the Inorder traversal in Tree.
Algorithm Inorder(tree)
1. Traverse the left subtree, i.e., call Inorder(left-subtree)
2. Visit the root.
3. Traverse the right subtree, i.e., call Inorder(right-subtree)
=> added Inorder Traversal in Python3 for Binary Trees

Searching/Binary Search/Binary Search - JavaScript.js
I added binary search algorithm in JavaScript for issue #3
=> Added Binary Search in JavaScript Issue : #3

Trees/LevelOrderTraversal/LevelOrderTraversal.java
=> Level Order Traversal for Binary Tree using Queue Added

Trees/Postorder_Traversal/Postorder_Traversal_python3.py, Trees/Preorder_Traversal/Preorder_Traversal_python3.py
Created different folders for Postorder and preorder 
Also Added postorder preorder implementation of trees using python3
Algorithm Preorder(tree)
1. Visit the root.
2. Traverse the left subtree, i.e., call Preorder(left-subtree)
3. Traverse the right subtree, i.e., call Preorder(right-subtree) 
Algorithm Postorder(tree)
1. Traverse the left subtree, i.e., call Postorder(left-subtree)
2. Traverse the right subtree, i.e., call Postorder(right-subtree)
3. Visit the root.
=> added Postorder, Preorder Traversal in Python3 for Binary Trees

Trees/Kruskal’s Minimum Spanning Tree/Kruskal’s Minimum Spanning Tree- Python.py, Trees/Kruskal’s Minimum Spanning Tree/Kruskal’s Minimum Spanning Tree.md
I have added in this pull request the python code for the process of finding the minimum cost spanning tree of a tree using Kruskal's Algorithm.
Along with it an .md file of the theoretical explanation is also added .
=> Added Kruskal's Min cost spanning tree algorithm

Lexicigraphically Smallest:Largest/lexicographically.py, Lexicigraphically Smallest:Largest/lexicographically_explain.txt
I have created python file and txt file for Lexicographically Smallest/largest substring of size k. It was fun to contribute. Let me know if any suggestions. Hope you like it.
=> Lexicographically Smallest/largest substring of size k

Linked Lists/Max/MaxOfLinkedList.c
added a program in c language to find the maximum element in a singly linked list
=> #3 fixed added max of linked list program

Greedy Algorithm/Algo explanation.txt, Greedy Algorithm/dijkstra algorithm.cpp
Code in C++ of Dijkstra algorithm with proper explanation of the algorithm in text file is added in new folder named Greedy
=> Added Dijkstra algorithm 

Searching/Linear Search/Linearsearch_adiksha20.java
Added a linear search file using java
=> Added linear search file in java

Strings/Lexicographically-smallest-largest/Lexicographically-smallest-largest-python.py, Strings/Lexicographically-smallest-largest/Lexicographically-smallest-largest-python.txt
I have changed the structure of the file names  for Lexicographically smallest-largest substring of size k. Please check it and let me know for further any changes. It was great to contribute.
=> Lexicographically smallest-largest substring

Linked Lists/Reverse LL/Reversing-Linkedlist-C++.cpp
Added C++ code for Reversing a LinkedList
=> Added Reversing-Linkedlist-C++.cpp

Trees/Fenwick_Tree/Fenwick_Python3.py
=> Implementation of Binary Indexed Tree in Python 3

Searching/Binary Search/Binary_Search-C.c
i feel its better to understand
=> more better code

Graphs/DFS-Traversal/DFSTraversal_Java.java
DFS traversal implementation in Java.
=> Added DFS Traversal in Graph in Java

Searching/Binary Search/Binary Search - Ruby.rb
Issue: https://github.com/tulika-99/DS_Algorithms/issues/3
=> Add Binary Search Algorithm in Ruby

Searching/Linear Search/LinearSearch.py
Started with basics. Will add more later.
=> Linear Search in Python

Graphs/cycle_detection/directed_graph_cycle_detection.cpp, Graphs/topological_sort/topological_sort.cpp
Added directed graph cycle detection code in c++
=> added cycle detection in directed graphs

Graphs/DFS-Traversal/DFS_Traversal_C++.cpp, Strings/Longest-common-subsequence/longest_common_subsequence-C++.cpp, Strings/Naive-pattern-matching-algorithm/naive_string_matching-C++.cpp
* Graphs
* Depth First Search(DFS) graph traversal algorithm in C++
* Strings
* Naive Pattern Searching algorithm in C++
* Solution of Longest Common Subsequence problem using Dynamic Programming in C++
=> Added 1 algorithm in Graphs category and 2 algorithms in Strings category

Graphs/Topological-Sorting/Topological_Sorting_Python3.py
Topological sort implementation in Python 3.
=> Added Topological Sort Python3 Implementation

Searching/Linear Search/Linear Search - Ruby.rb
Issue: https://github.com/tulika-99/DS_Algorithms/issues/3
=> Add Linear Search Algorithm in Ruby

Searching/Binary Search/BinarySearchPHP.php
Binary search with recursion for PHP
=> Added recursive binary search

Linked Lists/LL Insertion/LL_Insertion_nth_pos.c
Java Implemention of insertion in linked list at nth position of a list.
=> Insertion in LinkedList at nth position

Graphs/Dijkstra/Dijkstra_Python3.py
Returns the minimum cost to reach each node from the start node.
If a node is not reachable returns 'infinity'
=> Dijkstra Python 3 Implementation

Trees/Inorder_Traversal/inorder.c
I have inorder traversal of binary tree in c
=> Inorder Traversal in c

Trees/Diagonal Traversal/Diagonal Traversal-C++.cpp
Diagonal Traversal of nodes in a binary tree algorithm added in C++.
=> Added Diagonal Order Traversal of Binary Tree in C++

Graphs/Count Connected Components/Count_connected_components-C++.cpp
Added the following algorithm in Graphs category:
* **Problem:** Count the number if connected components in an undirected graph
* Added the solution of this problem in C++
=> Added an algorithm in Graphs category in C++

Graphs/Kruskal's Algorithm.cpp, Greedy_Algorithms/Weighted Job Scheduling/Weighted Job Scheduling.cpp
=> Kruskal's Algorithm.cpp

Graphs/BFS-Traversal/BFS_javascript.js, Graphs/DFS-Traversal/DFS_javascript.js
Hi @tulika-99 
I have implemented Graph DFS and BFS using Javascript. I will add more such algorithms using JS.
Thanks.
=> #Javascript# Graph BFS and DFS implementation

Strings/Robin Karp Algorithm/Robin Karp - CPP.cpp
Hello Tulika
I've added the implementation of the Robin Karp Algorithm in C++ Language. Please accept my pull request.
Thank you.
=> Added Robin Karp in CPP

Searching/Jump Search/JumpSearch.cs
Please review and merge @tulika-99 🙂
=> Add Jump Search C#

Linked Lists/LL Insertion/optimized_Insertion_LL.cpp
I have added a Added optimized Insertion Method to Insert in a Singly Linked List.
Using this  you can add a Particular Node at a specified position in Linked list.
I have added this program in the folder  DS_Algorithms  -> LinkedList -> LL insertion ->optimized_Insertion_LL.cpp 
hope u find it helpful and needful!!   : )
=> Added optimized Insertion Method to Insert in a linkedList

Bit Manipulation/Bit_Concept/Bit_Explaination.txt, Bit Manipulation/Bit_Concept/No_Of_Set_Bits.cpp, Bit Manipulation/Bit_Concept/Power_Of_2.cpp
implemented counting no. of set bits and power of 2 problem along with the implementation .please have a look : )
=>  Added one concept and a based problem in the bit manipulation

Number Theory/GCD/gcd - java.java
Hello Tulika
I've added the implementation of the GCD  in the Number Theory section in Java Language. Please review it, and if you find it useful then please accept my Pull Request.
Thank you.
=> Added gcd in java

Searching/Jump Search/jumpSearch.cpp
Hey,
I have added Jump Sort Algorithm in C++
=> Created jumpSearch.cpp

Linked Lists/Copy List With Random Pointers/QUESTION.md, Linked Lists/Copy List With Random Pointers/solution.cpp
Question as well as solution in C++ added for the said problem
=> Copy List With Random Pointers

Linked Lists/Reverse_a_linked_list_in_group_of_size_k.cpp
contributed code on linked list by reversing it in group of given size
=> reverse a linked list with group of k

Searching/Ternary-Search/Ternary-Search-Java.java
=> Added  Ternary-Search-Java 

Graphs/Euler Circuit/euler_circuit.cpp
Problem statement - Eulerian Path is a path in graph that visits every edge exactly once. Eulerian Circuit is an Eulerian Path which starts and ends on the same vertex. The task is to find that there exists the Euler Path or circuit or none in given undirected graph with V vertices and adjacency list adj. The task is to return 1 if graph contains Eulerian Path, 2 if graph contains Eulerian Circuit 0 otherwise.
=> detect euler circuit in graph: cpp solution added

Dynamic Programming/Fibonacci/fibonacci.js, Dynamic Programming/Fibonacci/fibonacci_DP.txt
Signed-off-by: gfmota <gabrielfmota134@gmail.com>
=> Add dynamic programming fibonacci

Arrays/Second-Largest-Element-in-an-array/secondLargestElement.cpp
I have added a program to compute the second largest element in an array. Please review.
=> added program to find second largest element in an array

Arrays/Kadane's algorithm/Kadane-csharp.cs
Kadane’s Algorithm. C# implementation
Thank you in advance
=> Kadane’s Algorithm. C# implementation

Arrays/Kadane's algorithm/Kadanes_Algorithm.py
I have implemented Kadane's Algorithm in Python. Please let me know if I need to make any changes.
=> Implemented Kadane's Algorithm in Python

Searching/Interpolation-Search/Interpolation-Search.java
Algorithm for Interpolation search in Java
=> Added Interpolation search in Java

Stacks/Balanced-Braces.cpp
This algorithm uses stack to check if a sentence, code contains balanced braces or not
=> Added algorithm for balancing braces

ShortestJobFirst.c
This algorithm is used to implement Shortest job first scheduling algorithm of OS
=> Added Shortest Job first algo of OS

Banker's_Algo.c
This is the Banker's Algorithm to determine if there's a safe state and deadlock can be avoided
=> Added Banker's Algorithm in C
